# Generated by Django 4.2.7 on 2025-09-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('total_lines', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('critical_issues', models.IntegerField(default=0)),
                ('major_issues', models.IntegerField(default=0)),
                ('minor_issues', models.IntegerField(default=0)),
                ('complexity_score', models.FloatField(default=0.0)),
                ('maintainability_index', models.FloatField(default=0.0)),
                ('test_coverage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('go', 'Go'), ('rust', 'Rust')], max_length=20)),
                ('content', models.TextField()),
                ('size_bytes', models.IntegerField()),
                ('lines_of_code', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('cyclomatic_complexity', 'Cyclomatic Complexity'), ('halstead_complexity', 'Halstead Complexity'), ('maintainability_index', 'Maintainability Index'), ('lines_of_code', 'Lines of Code'), ('code_duplication', 'Code Duplication')], max_length=50)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analyzer.codefile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analyzer.analysisreport')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=100)),
                ('rule_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Info')], max_length=20)),
                ('category', models.CharField(choices=[('security', 'Security'), ('performance', 'Performance'), ('maintainability', 'Maintainability'), ('reliability', 'Reliability'), ('style', 'Code Style'), ('complexity', 'Complexity'), ('duplication', 'Code Duplication')], max_length=20)),
                ('message', models.TextField()),
                ('line_number', models.IntegerField()),
                ('column_number', models.IntegerField(default=0)),
                ('code_snippet', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='analyzer.codefile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='analyzer.analysisreport')),
            ],
        ),
        migrations.AddField(
            model_name='codefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='analyzer.project'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.project'),
        ),
    ]
