# Generated by Django 4.2.7 on 2025-09-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codefile',
            options={'ordering': ['-created_at']},
        ),
    ]
